// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIqhxa0m_B1L2Tkgjm5CaYLi8inlQ4pg',
    appId: '1:545599354386:web:493a916b8363ff25088acb',
    messagingSenderId: '545599354386',
    projectId: 'shakoosh-cba53',
    authDomain: 'shakoosh-cba53.firebaseapp.com',
    storageBucket: 'shakoosh-cba53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBik-GkxI79IDwX7uaNLq9coMzW2Ew_bk',
    appId: '1:545599354386:android:e97a5b1b2c13742f088acb',
    messagingSenderId: '545599354386',
    projectId: 'shakoosh-cba53',
    storageBucket: 'shakoosh-cba53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-gDKAaS41xQNHQSmaOZQtyO-LdLihV2w',
    appId: '1:545599354386:ios:a37d844979620d3a088acb',
    messagingSenderId: '545599354386',
    projectId: 'shakoosh-cba53',
    storageBucket: 'shakoosh-cba53.appspot.com',
    iosClientId: '545599354386-mg1e69crl34fm74p2l1us1a6i9r25g7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-gDKAaS41xQNHQSmaOZQtyO-LdLihV2w',
    appId: '1:545599354386:ios:a37d844979620d3a088acb',
    messagingSenderId: '545599354386',
    projectId: 'shakoosh-cba53',
    storageBucket: 'shakoosh-cba53.appspot.com',
    iosClientId: '545599354386-mg1e69crl34fm74p2l1us1a6i9r25g7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
